#!/usr/bin/env python3
"""Generate/check a deterministic Python symbol and route inventory for this repo."""

from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUTPUT = ROOT / ".agents/skills/python-client-maintainer/references/code-inventory.md"


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = []
    positional = list(node.args.posonlyargs) + list(node.args.args)
    defaults_at = len(positional) - len(node.args.defaults)
    for index, arg in enumerate(positional):
        item = arg.arg
        if index >= defaults_at:
            item += "=?"
        args.append(item)
    if node.args.vararg:
        args.append("*" + node.args.vararg.arg)
    elif node.args.kwonlyargs:
        args.append("*")
    for arg, default in zip(node.args.kwonlyargs, node.args.kw_defaults):
        args.append(arg.arg + ("=?" if default is not None else ""))
    if node.args.kwarg:
        args.append("**" + node.args.kwarg.arg)
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    return f"{prefix}{node.name}({', '.join(args)})"


def route_of(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    routes = []
    for dec in node.decorator_list:
        if not isinstance(dec, ast.Call) or not isinstance(dec.func, ast.Attribute):
            continue
        if dec.func.attr != "route" or not dec.args:
            continue
        try:
            routes.append(str(ast.literal_eval(dec.args[0])))
        except Exception:
            pass
    return routes


def render() -> str:
    paths = [ROOT / "main.py", ROOT / "build.py", ROOT / "check_time.py"]
    paths.extend(sorted((ROOT / "src").rglob("*.py")))
    lines = [
        "# Code inventory",
        "",
        "> Generated by `scripts/project_inventory.py`; do not hand-edit. Current source wins on drift.",
        "",
    ]
    for path in paths:
        if not path.exists() or "__pycache__" in path.parts:
            continue
        raw = path.read_bytes()
        rel = path.relative_to(ROOT).as_posix()
        digest = hashlib.sha256(raw).hexdigest()[:12]
        try:
            source = raw.decode("utf-8-sig")
            tree = ast.parse(source, filename=rel)
        except (UnicodeDecodeError, SyntaxError) as exc:
            lines.extend([f"## `{rel}`", "", f"- parse error: `{exc}`", ""])
            continue
        doc = ast.get_docstring(tree) or ""
        summary = doc.strip().splitlines()[0] if doc.strip() else ""
        lines.extend([f"## `{rel}`", "", f"- sha256: `{digest}`"])
        if summary:
            lines.append(f"- purpose: {summary}")
        top_functions = [n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
        classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
        for fn in top_functions:
            suffix = "" if not route_of(fn) else " — routes: " + ", ".join(f"`{r}`" for r in route_of(fn))
            lines.append(f"- L{fn.lineno} `{signature(fn)}`{suffix}")
        for cls in classes:
            bases = ", ".join(ast.unparse(base) for base in cls.bases) or "object"
            lines.append(f"- L{cls.lineno} class `{cls.name}({bases})`")
            for member in cls.body:
                if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    lines.append(f"  - L{member.lineno} `{signature(member)}`")
        if not top_functions and not classes:
            lines.append("- no public Python symbols")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated inventory")
    mode.add_argument("--check", action="store_true", help="fail when the inventory is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    content = render()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != content:
            print(f"STALE: {output}")
            return 1
        print(f"OK: {output}")
        return 0
    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8", newline="\n")
        print(f"WROTE: {output}")
        return 0
    print(content, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
