# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['src'],  # ★ 让 PyInstaller 能在 src/ 下发现 config.* / gui.* / api.* 等业务包
    binaries=[],
    datas=[
        ('src', 'src'),
        # ('config', 'config'),  # ★ 2026-06-16 不再打包 config/：让用户直接在 exe 根目录编辑 config/active.json 切换环境
        ('logo', 'logo'),
    ],
    hiddenimports=[
        # ---- PySide6 ----
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'shiboken6',
        # ---- qfluentwidgets / qframelesswindow ----
        'qfluentwidgets',
        'qframelesswindow',
        'darkdetect',
        # ---- 业务包 ----
        'gui',
        'gui.theme',
        'gui.login_window',
        'gui.main_window',
        'gui.widgets',
        'gui.widgets.pagination',
        'gui.pages',
        'gui.pages.scan_task_page',
        'gui.pages.deal_page',
        'gui.pages.history_page',
        'gui.pages.calc_page',
        'api',
        'api.auth_client',
        'api.session',
        'database',
        'database.db_manager_v2',
        'config',
        'config.config',  # ★ session.py 动态 sys.path 导入，PyInstaller 分析阶段追踪不到
        'config.config_manager',
        'config.api_config',
        'excel',
        'excel.excel_calculator_final',
        # ---- 工具层 ----
        'utils',
        'utils.logger',
        # ---- 服务层 ----
        'services',
        'services.proxy_manager',
        'services.proxy_alert_notifier',
        'services.proxy_paywall',
        'services.proxy_switch_budget',
        'services.proxy_token_provider',
        'services.shenlong_client',
        'services.dingtalk_notify',
        # ---- 第三方 ----
        'webbrowser',
        'sqlite3',
        'win32com',
        'win32com.client',
        'pythoncom',
        'flask',
        'flask_cors',
        'werkzeug',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'tempfile',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.styles.font',
        'openpyxl.styles.alignment',
        'openpyxl.styles.border',
        'openpyxl.styles.side',
        'openpyxl.styles.pattern',
        'openpyxl.utils',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'openpyxl.xml',
        'openpyxl.xml.functions',
        'openpyxl.xml.constants',
        'et_xmlfile',
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.cookies',
        'requests.exceptions',
        'requests.models',
        'requests.sessions',
        'requests.utils',
        'urllib3',
        'urllib3.util',
        'urllib3.util.retry',
        'urllib3.util.url',
        'urllib3.connectionpool',
        'urllib3.poolmanager',
        'urllib3.response',
        'PIL',
        'PIL.Image',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        '_tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'pkg_resources',  # ★ PyInstaller 6.0 + setuptools>=67 兼容性：app 未使用，排除避免 jaraco 导入错误
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='扫号器',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
